import type { ExportSettings } from '../types/schema'

export function generateHeader(settings: ExportSettings): string {
  const date = new Date().toISOString().split('T')[0]
  return [
    '// =====================================================',
    `// SCRIPTUI PANEL: ${settings.panelName}`,
    '// Generated by ScriptUI Panel Maker',
    `// ${date}`,
    '// =====================================================',
    '//',
    '// To use in After Effects:',
    '//   1. Save as .jsx file',
    '//   2. Open ScriptUI Panels folder: File > Scripts > Install ScriptUI Panel',
    '//   3. Or run via: File > Scripts > Run Script File',
    '//',
    '// Search "TODO:" to find event handlers that need implementation.',
    '// =====================================================',
  ].join('\n')
}
